### ISSUE TITLE
Add open interval (i.e. press button lap)

### ISSUE THREAD

**Issue by Abasz** [jpickup/GarminTools#3]
Hi I've been using your parser and I was wondering whether it would be possible to add the option to set a workout step that completes on lap button press. This is possible in GC

Thanks in advance.

**Comment by jpickup** [comment]
Apologies, only just noticed a notification email for this in my spam folder, hence the delay in replying.​​

It certainly should be possible to add such a feature. I'd need to change the antlr grammar and then wire that into an intermediate class and finally emit the correct data in the FIT file. None of that sounds to be difficult.​​

I guess the only real question is what to call this in the workout language. It will replace the duration of a step (currently either distance or time) and still have an optional pace or HR target. Maybe "Open" is a good name? ​That would then have steps like:
Open    -- an open step no target, ends when user presses lap button
Open@4:00-5:00/km   -- an open step with a pace target
Open@Z4    -- an open step with an HR zone
etc.

How does that sound?

**Comment by jpickup** [comment]
That's implemented now. Did a quick test on my watch and it works. Please let me know if you have any problems and thanks for the suggestion.

**Comment by Abasz** [comment]
Hi thanks for your assistance. I must confess that while I was looking for alternative I found this program: https://github.com/mgifos/quick-plan that allows uploading directly to Garmin Connect and enables scheduling more flexibly (i can move a workout without connecting watch to PC). But since that was lacking named paces and I know zero about java and scala, I ended up implementing my own parser in javascript that allows direct upload to GC.

**Comment by jpickup** [comment]
Thanks for that link. An interesting approach quick-plan uses going direct to Garmin Connect - I'd not reslised that was possible without buying the Garmin developer license. I think I'll start experimenting with that now!

**Comment by Abasz** [comment]
Well, its done via imitating a browser call (so you need to follow redirects and the logging in is tricky as you need to extract the cookies . Its not exactly pretty but has been done in various languages. Quick-plan does not work me actually as (I think but cannot confirm) it does not comply with the necessary request http version. It should use 2.0.

Also there are some strange things in the Garmin API that are non-conventional (like including this header in certain request:             `NK: "NT"`... or using `"X-HTTP-Method-Override": "PUT"` with a POST request for editing :)

But if you search github I am pretty sure there should be a java version as well. I recommend looking for a project that is still maintained as Garmin changed some stuff around last year...
